export const QUERY_KEYS = Object.freeze({
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  GET_ALL_LEVELS: 'GET_ALL_LEVEL',
  GET_ALL_TOPICS: 'GET_ALL_TOPICS',
  POST_LEVEL_TOPIC: 'POST_LEVEL_TOPIC',

  GET_ALL_VIDEOS: 'GET_ALL_VIDEO',
  GET_VIDEO_ITEM: 'GET_VIDEO_ITEM',

  PODCAST_LIST: 'PODCAST_LIST',
  ALL_TOPICS: 'ALL_TOPICS',
  VIDEO_LIST: 'VIDEO_LIST',
  PODCAST_DETAIL: 'PODCAST_DETAIL',
});
