export const QUERY_KEYS = Object.freeze({
  PODCAST_LIST: 'PODCAST_LIST',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  ALL_TOPICS: 'ALL_TOPICS',
  GET_ALL_TOPICS: 'GET_ALL_TOPICS',
  GET_ALL_LEVELS: 'GET_ALL_LEVEL',
  POST_LEVEL_TOPIC: 'POST_LEVEL_TOPIC',
});
