export const QUERY_KEYS = Object.freeze({
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  GET_INFO_USER: 'GET_INFO_USER',
  POST_INFO_USER: 'POST_INFO_USER',

  GET_ALL_LEVELS: 'GET_ALL_LEVEL',
  GET_ALL_TOPICS: 'GET_ALL_TOPICS',
  POST_LEVEL_TOPIC: 'POST_LEVEL_TOPIC',

  GET_ALL_VIDEOS: 'GET_ALL_VIDEO',
  GET_VIDEOS_FEATURE: 'GET_VIDEOS_FEATURE',
  GET_VIDEO_ITEM: 'GET_VIDEO_ITEM',

  PODCAST_LIST: 'PODCAST_LIST',
  ALL_TOPICS: 'ALL_TOPICS',
  VIDEO_LIST: 'VIDEO_LIST',
  PODCAST_DETAIL: 'PODCAST_DETAIL',
  GET_POPULAR_TOPICS: 'GET_POPULAR_TOPICS',
  GET_SEARCH_RESULT: 'GET_SEARCH_RESULT',
  GET_SEARCH_HISTORY: 'GET_SEARCH_HISTORY',
  GET_GROUP_LIST: 'GET_GROUP_LIST',
  GET_SAVED_WORD_LIST: 'GET_SAVED_WORD_LIST',
  GET_SAVED_WORD_DETAIL: 'GET_SAVED_WORD_DETAIL',
  GET_AMOUNT_QUESTION_FOR_GAME_CHOOSE_RIGHT_WORD:
    'GET_AMOUNT_QUESTION_FOR_GAME_CHOOSE',
  GAME_CHOOSE_RIGHT_WORD_CHECK_RESULT_TRUE_OR_FALSE:
    'GAME_CHOOSE_RIGHT_WORD_CHECK_RESULT_TRUE_OR_FALSE',
  GAME_CHOOSE_RIGHT_WORD_GET_CORRECT_ANSWER:
    'GAME_CHOOSE_RIGHT_WORD_GET_CORRECT_ANSWER',
});
