export const HOME_PAGE = 'Home'
export const SEARCH_PAGE = 'Search'
export const VIDEO_DETAILS_PAGE = 'VideoDetails'
export const INTRO = 'Intro'
export const TOPIC = 'Topic'
export const START_DASHBOARD = 'StartDashboard'
export const LOGIN = 'Login'
export const INPUT_OTP = 'InputOTP'
